### ISSUE TITLE
[Feature Request] Empty X-Ray file

### ISSUE THREAD

**Issue by Vilhelm-Ian** [xxyzz/WordDumb#146]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

I don't want to wait for X-ray to automatically generate description for entries. I would rather do it myself. Is it possible  to generate an empty X-Ray file and then using custom X-Ray to generate description for the entries

### System Information

manjaro

### Error message

```text
no error message
```

### Reproduce steps

no error

**Comment by xxyzz** [comment]
I think I might misunderstand the issue, sorry for that...

Disable "fetch people" option might be little faster? I think the code is not that slow, you could wait a few minutes for most books then check the generated x-ray file, add some customized x-ray data for correction, run plugin again and this time it'll be much faster because MediaWiki API results are saved locally.
