### ISSUE TITLE
Can't edit cutom X-ray Entries

### ISSUE THREAD

**Issue by Vilhelm-Ian** [xxyzz/WordDumb#147]
### Checkboxes

- [X] I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
- [X] I have not found similar issue or disscussion at GitHub.
- [X] Reboot doesn't fix the problem.

### Describe the bug

When I double click the description of an entry Calibre crashes

### System Information

manjaro
current most recent version

### Error message

```text
None
```

### Reproduce steps

1. Open custom X-Ray
2. Double Click description of an entry

**Comment by xxyzz** [comment]
I can't reproduce the error, please at least post the error message.

**Comment by Vilhelm-Ian** [comment]
![image](https://github.com/xxyzz/WordDumb/assets/81630959/6b542fdd-193d-4955-b2ae-977201d8220c)
I removed xray_creator. And still on clicking the description multiple times calibre closes. Now I don't get an error in the terminal but calibre still crashes

**Comment by xxyzz** [comment]
I didn't notice the "Address boundary error" line, that error is not caused by the WordDumb plugin. Maybe it's a calibre bug, or Qt bug.

**Comment by Vilhelm-Ian** [comment]
![image](https://github.com/xxyzz/WordDumb/assets/81630959/d1508951-f364-482d-ad76-c5fd0f62dfd0)
this is the only plugin that I have installed

**Comment by xxyzz** [comment]
I not saying the SIGSEGV error is caused by other plugins, this kind of memory error is very unlikely caused by WordDumb's Python code. And I can't reproduce the error on Arch Linux, I guess manjaro is similar to Arch but I don't know if they changed the build file.

You could try to install the official binary file from https://calibre-ebook.com/download_linux
or edit the customize X-Ray json file in any text editor.

**Comment by Vilhelm-Ian** [comment]
a quick question. How can I make the changes to the json file be applied to the x-ray file already present in kindle. Do I have to click Create X-Ray file again

**Comment by xxyzz** [comment]
> Do I have to click Create X-Ray file again

Yes.
